name: Release action
# Call the reusable workflow release-solution-with-inputs.yml
# Release your solution to prod when you create a new release.

on:
  release:
      types: [created]        

jobs:
  Release-solution-ALMLab:
    uses: ./.github/workflows/release-solution-to-prod-with-inputs.yml
    with:
      #You can specify the solution name here
      solution_name: ALMLab
      #Update your values here
      BUILD_ENVIRONMENT_URL: https://orgf443f028.crm4.dynamics.com
      PRODUCTION_ENVIRONMENT_URL: https://org66590cdc.crm4.dynamics.com
      CLIENT_ID: 'da40d3e2-97de-4061-85dd-a0e392eca911'
      TENANT_ID: '2d15b601-9d9a-4c0b-896f-ace0662817bd'    
    secrets:
      envSecret: ${{ secrets.PowerPlatformSPN }}
